### ISSUE TITLE
希望能解决一下国内谱面仓库访问慢的问题

### ISSUE THREAD

**Issue by lgc2333** [Yuameshi/PhiCommunity#37]
# 运行环境

- 设备：LG V40 ThinQ
- 设备平台： Android 10
- 浏览器：PhiCommunity APP/Kiwi Browser95.0.4638.75
- 错误现象： 谱面资源加载极慢，开了Clash甚至是全局模式依然无法解决
- 错误Log：无

# 建议
- 可以把谱面仓库clone一份到gitee或者国内访问快一点的服务器

**Comment by HanHan233** [comment]
vc和cf都试过了嘛

**Comment by lgc2333** [comment]
有的时候全抽风，有的时候就非常快……

**Comment by Yuameshi** [comment]
没办法，我后续整个自定义源吧，不过获取API还是GitHub不会变
