### ISSUE TITLE
iPadOS上无法播放音频以及打歌时黑屏的bug

### ISSUE THREAD

**Issue by xuangeyouneihan** [Yuameshi/PhiCommunity#38]
# 运行环境

- 设备：iPad 2018

- 设备平台：iPadOS 15.4.1

- 浏览器：Apple Safari 15，夸克HD，Alook

- 错误现象：
  - Safari：无法播放背景音乐，所以无法根据声音调整偏移率，但是游玩时音频播放正常；
    夸克：可以正常播放背景音乐及根据声音调整偏移率，但是游玩时无法播放音频
    Alook：既无法正常播放背景音乐也无法在游玩时播放音频
  - 已经关闭深色模式，但仍然黑屏，看不见判定线和音符（三个浏览器都是如此）  
    ![439950FE-0493-406A-9E96-CCA89F4FA777](https://user-images.githubusercontent.com/50788434/162900524-155772b1-56a6-4c50-ad24-8862929eef62.png)
    ![0E5E5C3A-B0A0-4DBA-AD9F-F6B3355E9B91](https://user-images.githubusercontent.com/50788434/162902629-8d2e943a-daec-4a04-aad6-491f46c7dc54.png)
    ![53DFE99A-4FD8-488A-9982-7DE3BF651FAC](https://user-images.githubusercontent.com/50788434/162903449-5c01c872-76d0-4234-a4b6-ae08e1543086.png)

- 错误Log：没有Mac，BrowserStack只能免费试用1分钟，抓不了

**Comment by Yuameshi** [comment]
淦，我记得win也能抓日志来着（不过比较麻烦就是了

**Comment by Yuameshi** [comment]
你无痕试试，或者换夸克之类的（

**Comment by Yuameshi** [comment]
iOS 15.4/5是有这样的问题（

**Comment by DGCK81LNN** [comment]
iOS 15.5 Safari 可以复现，但特定情况下刷新页面又会莫名其妙地自动恢复正常。

用 bookmarklets 注入了一个 [VConsole](https://github.com/Tencent/vConsole)，没有看到控制台报错。（可信度不高，还请用正常方法调试

![截图中 VConsole 控制台显示“核心资源加载完成”，并显示了一个包含谱面数据的对象，没有显示任何错误。](https://user-images.githubusercontent.com/54282183/171827891-a5fabb76-8766-438d-9caf-e708f26dbe88.png)

**Comment by Yuameshi** [comment]
我记得是iOS15.4/5中的一个*安全更新*还是哪个禁止了从缓存加载贴图的问题，具体我也不是特别清楚，目前没有iOS设备调试

**Comment by yuameshi** [comment]
懒得修了，等Phigrim吧
