### ISSUE TITLE
想要spasmodic sp的谱面文件

### ISSUE THREAD

**Issue by TaoXiaoZ** [Yuameshi/PhiCommunity#39]
https://github.com/Yuameshi/phigros-charts-repo
能否添加spasmodic sp谱面？
如果添加麻烦联系我：frchz5408@gmail.com

**Comment by YigeXiaogeziAwa** [comment]
顺带一提，你提供的repo地址是phigros网页版的 他已经 archive 了

**Comment by Yuameshi** [comment]
是这样的，如果你能要到授权那肯定能加

**Comment by YigeXiaogeziAwa** [comment]
> 是这样的，如果你能要到授权那肯定能加

那确实 233
